# Generated by Django 4.1.1 on 2024-02-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_image_image_account_ima_created_ea74f6_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
